image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-browser
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
tasks:
  - command: |
      cd $HOME/eclipse-installer
      chmod +x eclipse-inst && ./eclipse-inst